[package]
name = "kani-domain"
version = "0.1.0"
edition = "2024"

[dependencies]
kani-domain-api-incoming = { workspace = true }
kani-domain-api-model = { workspace = true }
kani-domain-api-outgoing = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
blockhash = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
image = { workspace = true }
lz_fnv = { workspace = true }
regex = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
