[package]
name = "pantsu-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pantsu_server"
path = "src/bin/main.rs"

[lib]
name = "pantsu_lib"
path = "src/lib/lib.rs"

[dependencies]
pantsu-domain = { workspace = true }
pantsu-http-api = { workspace = true }
pantsu-fs = { workspace = true }
pantsu-iqdb = { workspace = true }
pantsu-worker = { workspace = true }
pantsu-postgres = { workspace = true }

byte-unit = { workspace = true }
chrono = { workspace = true }
figment = { workspace = true, features = ["env", "yaml"] }
serde = { workspace = true }
tokio = { workspace = true, features = ["macros"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
yansi = { workspace = true }

[features]
default = ["mock-user"]
mock-user = ["pantsu-http-api/mock-user"]
