[package]
name = "pantsu-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pantsu_server"
path = "src/bin/main.rs"

[lib]
name = "pantsu_lib"
path = "src/lib/lib.rs"

[dependencies]
pantsu-domain = { workspace = true }
pantsu-http-api = { workspace = true }
pantsu-fs-library = { workspace = true }
pantsu-iqdb = { workspace = true }
pantsu-worker = { workspace = true }

byte-unit = { workspace = true }
chrono = { workspace = true }
figment = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
yansi = { workspace = true }
